In [1]:
!pip install pandas
!pip install fredapi
!pip install yfinance

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in .\.venv\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: fredapi in .\.venv\Lib\site-packages (0.5.2)
Requirement already satisfied: pandas in .\.venv\Lib\site-packages (from fredapi) (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in .\.venv\Lib\site-packages (from pandas->fredapi) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas->fredapi) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas->fredapi) (2025.3)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas->fredapi) (1.17.0)
Requirement already satisfied: yfinance in .\.venv\Lib\site-packages (1.2.0)
Requirement already satisfied: pandas>=1.3.0 in .\.venv\Lib\site-packages (from yfinance) (3.0.1)
Requirement already satisfied: numpy>=1.16.5 in .\.venv\Lib\site-packages (from yfinance) (2.4.4)
Requirement already satisfied: requests>=2.31 in .\.venv\Lib\site-packages (from yfinance) (2.33.1)
Requirement already satisfied: multitasking>=0.0.7 in .\.venv\Lib\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in .\.venv\Lib\site-packages (from yfinance) (4.9.4)
Requirement already satisfied: pytz>=2022.5 in .\.venv\Lib\site-packages (from yfinance) (2026.1.post1)
Requirement already satisfied: frozendict>=2.3.4 in .\.venv\Lib\site-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in .\.venv\Lib\site-packages (from yfinance) (4.0.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in .\.venv\Lib\site-packages (from yfinance) (4.14.3)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in .\.venv\Lib\site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in .\.venv\Lib\site-packages (from yfinance) (7.34.1)
Requirement already satisfied: websockets>=13.0 in .\.venv\Lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in .\.venv\Lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in .\.venv\Lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2026.2.25)
Requirement already satisfied: soupsieve>=1.6.1 in .\.venv\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in .\.venv\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: pycparser in .\.venv\Lib\site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\.venv\Lib\site-packages (from requests>=2.31->yfinance) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in .\.venv\Lib\site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in .\.venv\Lib\site-packages (from requests>=2.31->yfinance) (2.6.3)

In [2]:
import pandas as pd

gold_data = pd.read_csv("C:/Users/ADMIN/Desktop/Gold-Silver-GeopoliticalRisk_HistoricalData.csv")
gold_data['DATE'] = pd.to_datetime(gold_data['DATE'])
gold_data.set_index('DATE', inplace=True)
gold_data = gold_data[gold_data.index >= '1999-01-01']
gold_data

,GOLD_PRICE,GOLD_OPEN,GOLD_HIGH,GOLD_LOW,GOLD_CHANGE_%,SILVER_PRICE,SILVER_OPEN,SILVER_HIGH,SILVER_LOW,SILVER_CHANGE_%,GPRD,GPRD_ACT,GPRD_THREAT,EVENT
DATE,,,,,,,,,,,,,,
2025-09-10,3630.90,3633.61,3634.42,3620.90,-0.07,40.92,40.89,40.94,40.72,0.09,NaN,NaN,NaN,NaN
2025-09-09,3633.61,3637.10,3674.75,3625.33,-0.06,40.89,41.34,41.50,40.77,-1.13,NaN,NaN,NaN,NaN
2025-09-08,3635.84,3586.82,3646.60,3579.67,1.24,41.36,41.01,41.68,40.51,1.20,117.26,97.42,146.26,NaN
2025-09-07,3591.19,3592.07,3596.56,3586.95,0.12,40.86,41.00,41.01,40.76,-0.34,83.51,111.00,92.59,NaN
2025-09-05,3586.81,3547.00,3600.33,3540.05,1.15,41.01,40.69,41.44,40.55,0.76,166.42,110.61,224.05,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999-01-08,291.25,291.05,291.25,291.25,-0.10,5.29,5.22,5.29,5.28,0.76,70.81,61.38,92.16,NaN
1999-01-07,291.55,288.25,291.55,291.55,1.32,5.25,5.16,5.25,5.23,1.55,68.03,64.87,59.03,NaN
1999-01-06,287.75,287.00,287.75,287.75,0.28,5.17,5.03,5.17,5.15,2.58,62.19,71.79,43.55,NaN
1999-01-05,286.95,287.65,286.95,286.95,-0.14,5.04,4.92,5.04,5.03,2.02,60.68,85.41,41.56,NaN
1999-01-04,287.35,288.55,287.35,287.35,-0.31,4.94,5.01,4.94,4.93,-1.98,54.95,62.60,39.16,NaN

In [6]:
from fredapi import Fred
fred = Fred(api_key="77607617679b9e388bc1c17f17bf0874")

end = '2025-09-10'
start = '1991-01-01'
df1 = pd.DataFrame({
'interest_rate' : fred.get_series('REAINTRATREARAT10Y', observation_start = start, observation_end = end),
'inflation_rate' : fred.get_series('FPCPITOTLZGUSA', observation_start = start, observation_end = end),
'expected_inflation' : fred.get_series('EXPINF10YR', observation_start = start, observation_end = end),
'gdp' : fred.get_series('GDP', observation_start = start, observation_end = end),
'10_year_treasury_note_yield' : fred.get_series('WM2NS', observation_start = start, observation_end = end),
'wti_crude_oil_price' : fred.get_series('POILWTIUSDM', observation_start = start, observation_end = end)})

In [12]:
import yfinance as yf

gold_futures = yf.download('MGC=F', start=start, end=end)
vix = yf.download('^VIX', start=start, end=end)
us_dollar = yf.download('DX-Y.NYB', start=start, end=end)
s_and_p_500 = yf.download('^GSPC', start=start, end=end)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [13]:
raw_data = pd.concat([df1, s_and_p_500, vix, us_dollar,gold_futures], axis=1)
raw_data

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_54064\3369747055.py:1: Pandas4Warning: Sorting by default when concatenating all DatetimeIndex is deprecated.  In the future, pandas will respect the default of `sort=False`. Specify `sort=True` or `sort=False` to silence this message. If you see this warnings when not directly calling concat, report a bug to pandas.
  raw_data = pd.concat([df1, s_and_p_500, vix, us_dollar,gold_futures], axis=1)

,interest_rate,inflation_rate,expected_inflation,gdp,10_year_treasury_note_yield,wti_crude_oil_price,"(Close, ^GSPC)","(High, ^GSPC)","(Low, ^GSPC)","(Open, ^GSPC)",...,"(Close, DX-Y.NYB)","(High, DX-Y.NYB)","(Low, DX-Y.NYB)","(Open, DX-Y.NYB)","(Volume, DX-Y.NYB)","(Close, MGC=F)","(High, MGC=F)","(Low, MGC=F)","(Open, MGC=F)","(Volume, MGC=F)"
1991-01-01,3.922931,4.234964,3.804597,6035.178,NaN,NaN,NaN,NaN,NaN,NaN,...,83.070000,83.430000,83.010002,83.370003,0.0,NaN,NaN,NaN,NaN,NaN
1991-01-02,NaN,NaN,NaN,NaN,NaN,NaN,326.450012,330.750000,326.450012,330.200012,...,82.790001,83.080002,82.660004,82.930000,0.0,NaN,NaN,NaN,NaN,NaN
1991-01-03,NaN,NaN,NaN,NaN,NaN,NaN,321.910004,326.529999,321.899994,326.459991,...,82.809998,82.930000,82.680000,82.889999,0.0,NaN,NaN,NaN,NaN,NaN
1991-01-04,NaN,NaN,NaN,NaN,NaN,NaN,321.000000,322.350006,318.869995,321.910004,...,83.360001,83.519997,82.599998,82.669998,0.0,NaN,NaN,NaN,NaN,NaN
1991-01-07,NaN,NaN,NaN,NaN,3309.9,NaN,315.440002,320.970001,315.440002,320.970001,...,84.669998,85.110001,84.540001,84.870003,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-09-03,NaN,NaN,NaN,NaN,NaN,NaN,6448.259766,6453.669922,6416.169922,6445.819824,...,98.139999,98.639999,98.010002,98.400002,0.0,3606.100098,3611.600098,3562.699951,3570.600098,17185.0
2025-09-04,NaN,NaN,NaN,NaN,NaN,NaN,6502.080078,6502.540039,6445.979980,6456.600098,...,98.349998,98.440002,98.080002,98.150002,0.0,3577.300049,3592.300049,3544.800049,3590.199951,17730.0
2025-09-05,NaN,NaN,NaN,NaN,NaN,NaN,6481.500000,6532.649902,6443.979980,6529.080078,...,97.769997,98.260002,97.430000,98.239998,0.0,3624.000000,3626.100098,3565.699951,3572.800049,16520.0
2025-09-08,NaN,NaN,NaN,NaN,22139.2,NaN,6495.149902,6508.669922,6483.290039,6498.089844,...,97.449997,97.940002,97.419998,97.790001,0.0,3648.500000,3656.600098,3592.899902,3610.000000,14150.0
2025-09-09,NaN,NaN,NaN,NaN,NaN,NaN,6512.609863,6518.229980,6483.080078,6503.330078,...,97.790001,97.820000,97.250000,97.379997,0.0,3653.300049,3685.899902,3634.500000,3652.000000,16775.0

In [15]:
raw_data.to_csv("C:/Users/ADMIN/Desktop/ECON 323/python stuff/raw_data.csv", index=True )